# Generated by Django 4.2.1 on 2023-11-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('leader', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=12)),
                ('City', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('profession', models.CharField(default='', max_length=50)),
                ('organisation', models.CharField(default='', max_length=50, null=True)),
                ('referral', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
