# Generated by Django 4.2.1 on 2023-11-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='referral',
            new_name='POC',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='leader',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='organisation',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='name',
            new_name='schoolname',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='track',
        ),
    ]
