# Generated by Django 4.2.1 on 2023-11-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0003_socioexhibition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socioexhibition',
            old_name='schoolname',
            new_name='myschool',
        ),
    ]
