# Generated by Django 4.2.1 on 2023-11-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0006_rename_city_socioexhibition_city_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socioexhibition',
            old_name='City_a',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='socioexhibition',
            old_name='POC_a',
            new_name='POC',
        ),
        migrations.RenameField(
            model_name='socioexhibition',
            old_name='address_a',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='socioexhibition',
            old_name='email_a',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='socioexhibition',
            old_name='principal_a',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='socioexhibition',
            old_name='profession_a',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='socioexhibition',
            old_name='schoolname_a',
            new_name='schoolname',
        ),
        migrations.RenameField(
            model_name='socioexhibition',
            old_name='state_a',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='socioexhibition',
            name='phone_a',
        ),
        migrations.AddField(
            model_name='socioexhibition',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
