# Generated by Django 4.2.1 on 2023-11-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0012_adhikar_jr_reg_adhikar_reg_mootcourt_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='Socio_quiz_reg',
        ),
    ]
