# Generated by Django 4.2.1 on 2023-11-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0013_rename_useraccount_socio_quiz_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio_quiz_reg',
            old_name='address',
            new_name='College_Name',
        ),
        migrations.RenameField(
            model_name='socio_quiz_reg',
            old_name='schoolname',
            new_name='team_leader_Name',
        ),
        migrations.RemoveField(
            model_name='socio_quiz_reg',
            name='POC',
        ),
        migrations.RemoveField(
            model_name='socio_quiz_reg',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='socio_quiz_reg',
            name='profession',
        ),
    ]
