# Generated by Django 4.2.1 on 2023-11-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0015_rename_address_mootcourt_reg_college_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhikar_jr_reg',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='adhikar_reg',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='hackathonregistration',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='pil_draft',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='socio_quiz_reg',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='socioexhibition',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='spf_reg',
            name='profession',
        ),
    ]
