# Generated by Django 4.2.1 on 2023-11-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0016_remove_adhikar_jr_reg_profession_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spf_reg',
            old_name='address',
            new_name='College_Name',
        ),
        migrations.RenameField(
            model_name='spf_reg',
            old_name='schoolname',
            new_name='team_leader_Name',
        ),
        migrations.RemoveField(
            model_name='spf_reg',
            name='POC',
        ),
        migrations.RemoveField(
            model_name='spf_reg',
            name='principal',
        ),
    ]
