# Generated by Django 4.2.1 on 2023-12-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0017_rename_address_spf_reg_college_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socio_quiz_reg',
            new_name='Socio_trivia_reg',
        ),
    ]
