# Generated by Django 4.2.1 on 2023-12-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0018_rename_socio_quiz_reg_socio_trivia_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adhikar_jr_reg',
            new_name='mock_parliament_reg',
        ),
        migrations.RenameModel(
            old_name='SPF_reg',
            new_name='union_budget_reg',
        ),
    ]
