# Generated by Django 4.2.1 on 2023-12-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0019_rename_adhikar_jr_reg_mock_parliament_reg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='address',
            new_name='member1',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='schoolname',
            new_name='member2',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='City',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='POC',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='state',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='email2',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='email3',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='member3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='phone2',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='phone3',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='teamname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
