# Generated by Django 4.2.1 on 2023-12-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0020_rename_email_casestudy_email1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathonregistration',
            old_name='phone',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='hackathonregistration',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='hackathonregistration',
            old_name='schoolname',
            new_name='member1',
        ),
        migrations.RenameField(
            model_name='pil_draft',
            old_name='phone',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='pil_draft',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='pil_draft',
            old_name='schoolname',
            new_name='member1',
        ),
        migrations.RemoveField(
            model_name='hackathonregistration',
            name='City',
        ),
        migrations.RemoveField(
            model_name='hackathonregistration',
            name='POC',
        ),
        migrations.RemoveField(
            model_name='hackathonregistration',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='hackathonregistration',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pil_draft',
            name='City',
        ),
        migrations.RemoveField(
            model_name='pil_draft',
            name='POC',
        ),
        migrations.RemoveField(
            model_name='pil_draft',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='pil_draft',
            name='state',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='address',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='comments',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='email2',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='email3',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='email4',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='member2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='member3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='member4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='phone1',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='phone2',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='phone3',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='phone4',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='teamname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pil_draft',
            name='email2',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='pil_draft',
            name='email3',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='pil_draft',
            name='member2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pil_draft',
            name='member3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pil_draft',
            name='phone1',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='pil_draft',
            name='phone2',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='pil_draft',
            name='phone3',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='pil_draft',
            name='teamname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hackathonregistration',
            name='address',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='pil_draft',
            name='address',
            field=models.CharField(default='', max_length=12),
        ),
    ]
