# Generated by Django 4.2.1 on 2023-12-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0022_rename_address_mock_parliament_reg_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mootcourt_reg',
            old_name='phone',
            new_name='College',
        ),
        migrations.RenameField(
            model_name='mootcourt_reg',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='mootcourt_reg',
            old_name='College_Name',
            new_name='member1',
        ),
        migrations.RenameField(
            model_name='mootcourt_reg',
            old_name='team_leader_Name',
            new_name='member2',
        ),
        migrations.RemoveField(
            model_name='mootcourt_reg',
            name='City',
        ),
        migrations.RemoveField(
            model_name='mootcourt_reg',
            name='state',
        ),
        migrations.AddField(
            model_name='mootcourt_reg',
            name='comments',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mootcourt_reg',
            name='email2',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='mootcourt_reg',
            name='email3',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='mootcourt_reg',
            name='member3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mootcourt_reg',
            name='phone1',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mootcourt_reg',
            name='phone2',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mootcourt_reg',
            name='phone3',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mootcourt_reg',
            name='teamname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
