# Generated by Django 4.2.1 on 2023-12-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiapp', '0023_rename_phone_mootcourt_reg_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio_trivia_reg',
            old_name='principal',
            new_name='School_UDISE',
        ),
    ]
